### ISSUE TITLE
你好，我验证了一下，之前的问题确实修复了，我看你改了不少地方，还没来得及梳理，不过当order【 new BPlusTree<>(3)】指定为3的时候，会报错，应该是边界处理没有完善     

### ISSUE THREAD

**Issue by zuiyue** [Morgan279/MemoryBasedBPlusTree#2]
BPlusTree<Integer, Integer> bPlusTree = new BPlusTree<>(3);

**Comment by zuiyue** [comment]
//我对这里做了修复，你看看合不合理    

@Override
        public BPlusTreeNode insert(K entry, V value) {

            BPlusTreeNode newChildNode = children.get(entryIndexUpperBound(entry)).insert(entry, value);

            if (newChildNode != null) {
                K newEntry = findLeafEntry(newChildNode);
                int newEntryIndex = entryIndexUpperBound(newEntry);

                entries.add(newEntryIndex, newEntry);
                children.add(newEntryIndex + 1, newChildNode);
                //3 2  1
                if (entries.size() > KEY_UPPER_BOUND) {
                    BPlusTreeNonLeafNode newNonLeafNode = split();
                    newNonLeafNode.entries.remove(0);
                    return newNonLeafNode;
                }

            }

            return null;
        }

**Comment by Morgan279** [comment]
你好， 经排查，确实存在上述的问题。

以前发生上溢情况下的插入逻辑是先分裂，然后再分情况将新节点插入旧节点或者新分裂出的节点；而你的修复逻辑是先进行插入，然后如果上溢则直接分裂，我认为这个修改是合理的，且因为少了一步判断所以代码实现起来会更加简洁。

我按照你的思路对代码进行了重构，修复了上面的问题，最新的代码已推送至主分支。
